name: Process and Convert AI List

on:
  workflow_dispatch:

  schedule:
    - cron: '0 22 * * *'

jobs:
  download-and-process:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download list and save as *.yaml
      - name: Download AI.list
        run: |
          curl -L "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/AI.list" -o AI.yaml

      # Step 3: Download sing-srs-converter
      - name: Download sing-srs-converter
        run: |
          curl -L "https://github.com/PuerNya/sing-srs-converter/releases/download/v2.0.1/sing-srs-converter-v2.0.1-linux-x86_64" -o sing-srs-converter
          chmod +x sing-srs-converter

      # Step 4: Filter and modify *.yaml
      - name: Process yaml
        run: |
          sed -i 's/ //g' *.yaml
          sed -i '/^.*IP-CIDR[^,]*,/ s/,no-resolve//' *.yaml

      # Step 5: Convert yaml using sing-srs-converter
      - name: Convert yaml
        run: |
          ./sing-srs-converter *.yaml

      # Step 6: Commit and push changes
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .  # 修改这里，添加所有更改
          git status  # 可选，打印状态以便调试
          git commit -m "Update converted files" || echo "No changes to commit"  # 如果没有更改，则不会出错
          git push
